> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [20]:
!pip install jovian --upgrade -q

In [21]:
import jovian

In [ ]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [2]:
import numpy as np

In [3]:
# List of functions explained 
function1 = np.full
function2 = np.concatenate
function3 = np.around
function4 = np.linspace
function5 = np.split

## Function 1 - np.full (change this)

Add some explanation about the function in your own words

In [5]:
#Function 1_ Example 1 - working
np.full((2, 3), 3.33)

# Example 2 - working
np.full((10, 3), (10, 1000, 1000000))

array([[     10,    1000, 1000000],
       [     10,    1000, 1000000],
       [     10,    1000, 1000000],
       [     10,    1000, 1000000],
       [     10,    1000, 1000000],
       [     10,    1000, 1000000],
       [     10,    1000, 1000000],
       [     10,    1000, 1000000],
       [     10,    1000, 1000000],
       [     10,    1000, 1000000]])

# Function 2: Concatenate

In [6]:
# Function 2- Example 1 - working

x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
y = np.array([[13, 14, 15, 16]])

np.concatenate((x, y), axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

Explanation about example

In [7]:
# Function 2_ Example 2 - working

x = np.array([[1, 2, 3], [5, 6, 7], [9, 10, 11]])
y = np.array([[4, 8, 12]])

np.concatenate((x, y.T), axis=1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Some closing comments about when to use this function.

In [8]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/yichenue/numpy-array-operations


'https://jovian.ai/yichenue/numpy-array-operations'

## Function 3 - NP.Around

Add some explanations

In [9]:
# Example 1 - working
import numpy as np

array=([6160115.379, 6160115.456])

np.around(array, decimals=2)



array([6160115.38, 6160115.46])

Explanation about example

In [10]:
# Example 2 - working
array=([6160115.379, 6160115.456])

np.around(array, decimals=-2)

array([6160100., 6160100.])

Explanation about example

In [11]:
# Example 3 - breaking (to illustrate when it breaks)

array=([6160115.379, 6160115.456])

np.around(array, decimals=-0.5)

TypeError: integer argument expected, got float

We have to use whole numbers, for this function to work.

Very useful when we need to change precision of our data sets.

Some closing comments about when to use this function.

In [12]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "yichenue/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/yichenue/numpy-array-operations


'https://jovian.ai/yichenue/numpy-array-operations'

# Function 4 - np.linspace

Add some explanations

In [13]:
# Example 1 - working
import jovian

import numpy as np

np.linspace(6160115.816, 6160150.152, num=5)

array([6160115.816, 6160124.4  , 6160132.984, 6160141.568, 6160150.152])

Explanation about example

In [14]:
# Example 2 - working
np.linspace(6160115.816, 6160150.152, num=5, endpoint=False, retstep=True)

(array([6160115.816 , 6160122.6832, 6160129.5504, 6160136.4176,
        6160143.2848]),
 6.867200000025332)

Explanation about example

In [17]:
# Example 3 - breaking (to illustrate when it breaks)
np.linspace(1, 5, 10, num=5)

TypeError: _linspace_dispatcher() got multiple values for argument 'num'

The interval can only have start and end number.

Very useful when we need to space numbers evenly.

In [18]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "yichenue/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/yichenue/numpy-array-operations


'https://jovian.ai/yichenue/numpy-array-operations'

## Function 5 - np.split

Add some explanations

In [19]:
# Example 1 - working
a = np.arange(21)

np.split(a, 7)

[array([0, 1, 2]),
 array([3, 4, 5]),
 array([6, 7, 8]),
 array([ 9, 10, 11]),
 array([12, 13, 14]),
 array([15, 16, 17]),
 array([18, 19, 20])]

Explanation about example

In [21]:
# Example 2 - working
b = np.arange(10)

np.split(b, [2, 7, 20])

[array([0, 1]),
 array([2, 3, 4, 5, 6]),
 array([7, 8, 9]),
 array([], dtype=int64)]

Explanation about example

In [22]:
# Example 3 - breaking (to illustrate when it breaks)
c = np.arange(9)

np.split(c, 10)

ValueError: array split does not result in an equal division

In the example above, we can see that the split must reslut into n-equal arrays.

Another great tool to manage data set.

In [23]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "yichenue/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/yichenue/numpy-array-operations


'https://jovian.ai/yichenue/numpy-array-operations'

In [24]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "yichenue/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/yichenue/numpy-array-operations


'https://jovian.ai/yichenue/numpy-array-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [30]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'